apiVersion: apps/v1
kind:
metadata:
  name:
  namespace:
spec:
  selector:
    matchLabels:
      app:
  replicas:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
        - name:
          image:
          ports:
            - containerPort:
          env:
            - name:
              value:

