apiVersion: v1
kind: Secret
metadata:
  name: meran-secrets
  namespace: apis-ns
type: Opaque
data:
  meran-secret-one: RmVkZSBkaWNlIHF1ZSBlbCBlcXVpcG8gZGUgQVBJcyBlcyBlbCBtZWpvciEhIQ==
  meran-secret-two: RW1pIGRpY2UgcXVlIGVsIGVxdWlwbyBkZSBEZWx0YSBlcyBlbCBtZWpvciEhIQ==
